#include "infrared_sensor.h"

void init_infrared_sensor_pin(void) {
#ifdef INFRARED_VCC_ENABLE
	INFRARED_SENSOR_DDR = (INFRARED_SENSOR_DDR & ~(INFRARED_SENSOR_PIN_MASK)) | INFRARED_SENSOR_GND_PIN_MASK | INFRARED_SENSOR_VCC_PIN_MASK;
	INFRARED_SENSOR_PORT = (INFRARED_SENSOR_PORT & ~(INFRARED_SENSOR_GND_PIN_MASK)) | INFRARED_SENSOR_PIN_MASK | INFRARED_SENSOR_VCC_PIN_MASK;
#else
	INFRARED_SENSOR_DDR &= ~(INFRARED_SENSOR_PIN_MASK);
	INFRARED_SENSOR_PORT &= ~INFRARED_SENSOR_PIN_MASK;
#endif // INFRARED_VCC_ENABLE
}